# Generated by Django 5.1.6 on 2025-02-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
