# Generated by Django 5.1.6 on 2025-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0002_remove_appointment_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="breed",
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[("admitted", "Admitted"), ("discharged", "Discharged")],
                default="admitted",
                max_length=10,
            ),
        ),
    ]
