# Generated by Django 5.1.6 on 2025-03-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "veterinary",
            "0003_animal_appointment_contact_medicine_animaldiagnosis_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="subject",
        ),
    ]
